title: "UFAX24 - UFAPRO888s แทงบอล หวย คาสิโน สล็อต บทความ"  # this means to ignore newlines until "show_excerpts:"

description: "แทงบอล หวย คาสิโน สล็อต บทความเป็นเว็บ ตรง มั่นคง และ ปลอดภัย สามารถเล่นได้บนมือถือ พร้อมทั้งโปรโมชั่นสุดพิเสษและ กิจกรรมดีๆอีกมากมาย UFAX24 - UFAPRO888s"

baseurl: "/"
url: "https://ufapro888.netlify.app" # change this URL, this is needed for generating right sitemap

permalink: "/blog/:title/"

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-purgecss
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  uglifier_args:
    harmony: true

image: "https://ufax24.com/wp-content/uploads/2021/06/7_820x350-Bank-2n-4.jpg"
locale: "th-TH"
author: "pnck dev app"

twitter:
  username: "ufax24"
  card: "summary"

facebook:
  app_id: "2910681209183952"
  publisher: "ufax249999"
  admins: "100070873703690"

webmaster_verifications:
  google: "8wKoeyxcK-fwaReKe5zMDZGwmfefvbrYtLp2h9GT1gE"
  bing: "343507645CB8E2A0D21C9D4976C705D3"
  alexa: ""
  yandex: "439a49a8d4f17558"
  baidu: ""


soopr:
  publish_token: "qVe6vfoozhRTgn21G5xSnBc7" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
